### PR TITLE
feat(django): added support for django 1.11 and remove support 1.9

### PR DESCRIPTION
**Pull request by galuszkak**
Django 1.11 is new LTS version and django 1.9 ended is support on April 2017 so it should be discourage to use as it has lack of security patches.

### CODE REVIEW

**Comment by galuszkak** [comment]
Pleasre review and merge, sounds test are passing. Probably will be contributing again @plq 👍  (great job with maintaining Spyne) with Soap 1.2 :)

**Comment by plq** [comment]
hey, glad to see you back!

**Comment by plq** [comment]
Do you think it's ok to remove anything <1.9?

**Comment by galuszkak** [comment]
No. 1.8 is still supported so this should stay. We should just discourage using for now 1.9 and encourage to upgrade to either 1.10 or 1.11.

For now it looks that to December 2017 there will be support for 1.10 and April 2018 for Django 1.8.

**Comment by plq** [comment]
ok. thanks for the info.

**Pull request merged**
