### PR TITLE
interface add method validate attr element_form_default

### PR DESCRIPTION
**Pull request by PyGuDev**
interface add method validate attr element_form_default
class application add attribute element_form_default

### CODE REVIEW

**Comment by PyGuDev** [comment]
Hello, is this implementation suitable for the project?

**Comment by plq** [comment]
hey, first, thanks for the patch.

i only had time to have a cursory look at this and it looked to me that the interface class is not meant to be used like that. i'll write a proper review once i have some time

**Comment by PyGuDev** [comment]
I think it fits. The ``Interface`` class contains all the information needed to create an interface document. The elementFormDefault attribute affects how the document is built.

**Comment by PyGuDev** [comment]
Ok. I will wait for your decision

**Comment by PyGuDev** [comment]
Hey. Could you see my changes today

**Comment by plq** [comment]
let me know what you think about https://github.com/arskom/spyne/commit/ef6e891a063d5a4ce10d2e205fefc7fc164f6c1e#diff-7f9e989508aa29f53e867133702ff0deacd99652718ac9863af5b075d40b3b0d

**Comment by PyGuDev** [comment]
Upon receipt of the scheme, everything works out and we get the elementFormDefault="unqualified" scheme. When we try to submit a request, it fails validation. When we specify `protocol=Soap 11(validation='lxml')` in the application, during initialization, the `set_app` method is called, which generates the validation scheme, it is necessary that `elementFormDefault="unqualified"` be specified at this moment

**Comment by plq** [comment]
ah, good point. let me see what i can do

**Comment by PyGuDev** [comment]
This way the validation works correctly

**Comment by PyGuDev** [comment]
How do you like this option?

**Comment by plq** [comment]
please don't violate pep8

**Comment by PyGuDev** [comment]
corrected

**Comment by PyGuDev** [comment]
Could you take a look at the option I propose today. This moment is important for the service I'm working on.

**Comment by PyGuDev** [comment]
Why is the xml_schema attribute here? Can wsdl11 be used?
```
class InterfaceDocumentsBase(object):
    def __init__(self, interface,
                 # *, # kwargs start here, commented due to py2 compat
                 xml_schema, wsdl11):
        self.interface = interface
        self.xml_schema = xml_schema
        self.wsdl11 = wsdl11
```

Can wsdl11 be used?
```
class InterfaceDocumentsBase(object):
    def __init__(self, interface,
                 # *, # kwargs start here, commented due to py2 compat
                 wsdl11):
        self.interface = interface
        self.wsdl11 = wsdl11

    @property
    def xml_schema(self):
        from spyne.interface import XmlSchema
        assert isinstance(self.wsdl11, XmlSchema)
        return self.wsdl11
```
How do you like the option that I propose in the committee?

**Comment by plq** [comment]
technically, element_form_default is an attribute of the xml schema, not wsdl. so in the code, it must be read from xml_schema

however, as wsdl inherits from xml schema, i did not want to duplicate the two and just return wsdl object as xml schema.

it's a readability enhancement for people who are reading the code and who are not you or me

**Comment by plq** [comment]
and why did you delete it? it didn't work?

**Comment by PyGuDev** [comment]
If I define interface like this it works
```
class MyInterfaceDocuments(InterfaceDocumentsBase):
    def __init__(self, interface):
        assert isinstance(interface, Interface)
        super(MyInterfaceDocuments, self).__init__(
            interface=interface,
            xml_shema=XmlSchema(interface, element_form_default='unqualified'),
            wsdl11=Wsdl11(interface, element_form_default='unqualified'),
        )

```
And if I want to initialize the application without the documents_container parameter, it crashes with an error

**Comment by PyGuDev** [comment]
```
    self.xml_schema = xml_shema
AttributeError: can't set attribute
```

**Comment by plq** [comment]
how are you testing it? can you commit the test as well?

**Comment by PyGuDev** [comment]
local run  helloworld_soap_unqual.py
run tox

**Comment by plq** [comment]
jenkins, run tests

**Comment by plq** [comment]
jenkins, run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by PyGuDev** [comment]
@arskom-jenkins run tests

**Comment by PyGuDev** [comment]
Added a fix, now the test passes

**Comment by PyGuDev** [comment]
jenkins, run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by PyGuDev** [comment]
You forgot to commit this commit

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by PyGuDev** [comment]
https://github.com/vmware/vsphere-automation-sdk-python/issues/285#issuecomment-918166848

**Comment by plq** [comment]
> [vmware/vsphere-automation-sdk-python#285 (comment)](https://github.com/vmware/vsphere-automation-sdk-python/issues/285#issuecomment-918166848)

yes, found this: https://github.com/suds-community/suds

**Comment by plq** [comment]
@arskom-jenkins run tests

**Comment by plq** [comment]
:partying_face: 

thanks for your help.

**Comment by PyGuDev** [comment]
And thank you.

**Comment by bgermann** [comment]
Can we expect a release soon that contains this?

**Comment by plq** [comment]
Yes, I merged bunch of other stuff as well. So 2.14.0 will be out this week most probably.

**Pull request merged**
