### PR TITLE
fix namespaces for soap12 faults

### PR DESCRIPTION
**Pull request by xavfernandez**

### CODE REVIEW

**Comment by plq** [comment]
waiting for travis...

**Comment by xavfernandez** [comment]
Well, I've just seen the Fault Reason isn't ok also, it should contain Text element:

    <env:Reason>
      <env:Text xml:lang="en">Sender Timeout</env:Text>
    </env:Reason>

cf http://www.w3.org/TR/2007/REC-soap12-part1-20070427/#faultstringelement

**Comment by xavfernandez** [comment]
Any clue where I could get the actual lang of the faultstring ?
I was thinking about adding it to Fault ? Or maybe I could just hardcode it as 'en' for now ?

**Comment by plq** [comment]
Ok.

Btw, you should use https://github.com/xavfernandez/spyne/blob/d7f39540bacf537f76e191d2c19b335e5246b068/spyne/const/xml.py#L81-82

these look way cleaner than doing e.g. `"{%s}Subcode" % self.ns_soap_env` yourself.

**Comment by plq** [comment]
> Any clue where I could get the actual lang of the faultstring ?

You can do `getattr(fault, 'lang', 'en')`

**Comment by xavfernandez** [comment]
ok, good idea, will do

**Comment by plq** [comment]
Please see: https://github.com/arskom/spyne/pull/386 from @galuszkak .

I'd objected to the fault object there because it introduced a completely different Fault object.

How do you think we should design the new Fault object for Soap 1.2 ?

**Comment by galuszkak** [comment]
For now It's just generating standard object from class Fault from spyne into soap 1.2 message. But In long term this should be done somehow different, as I don't think this is best aproach.

**Comment by xavfernandez** [comment]
concerning SOAP12_ENV instead of "{%s}Subcode" % self.ns_soap_env,
I'm not sure it is a good idea: sticking to self.ns_soap_env is what gave the possibility to inherit Soap11 and XmlDocument.

**Comment by plq** [comment]
> concerning SOAP12_ENV instead of "{%s}Subcode" % self.ns_soap_env,
> I'm not sure it is a good idea: sticking to self.ns_soap_env is what gave the possibility to inherit Soap11 and XmlDocument.

ok that's fine

**Comment by xavfernandez** [comment]
and concerning SOAP 1.2 faults, I'm tempted to either:

a) add a lang attribute to Fault, defaulting to spyne.DEFAULT_LANGUAGE and: 
   - in soap11, put the faultstring
   - in soap12, put only one Text subelement in Fault.Reason with xml:lang = fault.lang

or

b) add a dict Fault.translations attribute, with (lang, translated_reason) key-value pairs and if not present, fallback on case a)

**Comment by xavfernandez** [comment]
removed the issue with six

**Comment by plq** [comment]
So this is the plan?

```
    raise Fault(translations[lang], lang=lang)
```

**Comment by xavfernandez** [comment]
Well I went with solution a), so something like:

    raise Fault("Client.SomeError", "Une erreur est apparue", lang='fr')

For solution b), it would be more like:

    raise Fault("Client.SomeError",
                translations={'fr': 'Trop gros', 'en': 'Too big'})

**Comment by plq** [comment]
How would you choose which translation to actually put inside the error?

**Comment by xavfernandez** [comment]
In soap12 you would put all of them and in soap11, you would try to get the translation of Fault.lang and if not choose one randomly or crash.

**Comment by plq** [comment]
If we're to support string substitution inside translations, we should have a for loop that iterates over all of the supported languages and does something along the lines of: https://github.com/arskom/spyne/blob/master/spyne/error.py#L77-80

**Comment by xavfernandez** [comment]
This becomes more complicated, maybe we could stay with option a) and option b) will be implemented when the need arises ?

**Comment by plq** [comment]
I agree.

**Comment by plq** [comment]
ok, so this looks fine. let me look at it once more.

**Comment by plq** [comment]
thank you very much for your time.

**Comment by xavfernandez** [comment]
No problem :)
Thanks for spyne :+1:

**Pull request merged**
