### PR TITLE
Python 3 Compat

### PR DESCRIPTION
**Pull request by plq**

### CODE REVIEW

**Comment by plq** [comment]
jenkins, run tests.

**Comment by plq** [comment]
jenkins, run stable tests

**Comment by plq** [comment]
jenkins, run stable tests.

**Comment by backbord** [comment]
Hi @plq,

thanks for the great work on spyne!

I noticed that you're working on finalizing MTOM/XOP support and I'm really looking forward to that.
When looking through the changes and comparing with old soaplib behavior, I came across the use of `b2a_base64(payload)` where I believe that the old soaplib had `base64.b64encode(payload)`. At least [since Python 3.6.](https://docs.python.org/3.8/library/binascii.html#binascii.b2a_base64) there seems to be a difference: `base64.b64encode(s)` calls `b2a_base64(s, newline=False)`.

I'm not sure if this is helpful at all, but perhaps the `newline=False` parameter is required for backward compatibility. I'm not versed enough in MTOM/XOP to elaborate, but noticed some of my tests failing due to the newline.

Thanks and best regards!

**Comment by backbord** [comment]
Hi @plq again,

I do believe that there's a small mistake in the change of `collapse_swa()`:
Instead of 
```python
msg_string = chain((msg_string.encode(charset),), (e for e in envelope))
msg_string = generator.NL.encode('ascii').join(msg_string)
```
it should read
```python
msg_string = chain((msg_string.encode(charset), generator.NL.encode('ascii')), (e for e in envelope))
msg_string = ''.encode('ascii').join(msg_string)
```
(or similar)
as the envelope is an iterable of the chunks (e.g. from `__wsgi_input_to_iterable()`) and must not have newlines added in between chunks.

Thanks and best regards!

**Comment by plq** [comment]
Hello backbord,

Thanks for the kind words!

> I'm not sure if this is helpful at all, but perhaps the newline=False parameter is required for backward compatibility. I'm not versed enough in MTOM/XOP to elaborate, but noticed some of my tests failing due to the newline.

not base64 nor xml care about newlines, so this is fine

**Comment by plq** [comment]
As for your code change suggestion;

``''.encode('ascii')`` is just ``b''`` so not needed. as for the other changes, these seem fine. Why not send a pull request so we can discuss them properly, run tests on them etc.

**Comment by backbord** [comment]
I agree. It's been a while since I wrote something that might have needed to run in both python 2 and 3, so I wasn't sure about bytestrings. 😅

Thanks for the suggestion. I'll put a PR together. 👍

**Pull request merged**
