### PR TITLE
bare empty request are not allowed

### PR DESCRIPTION
**Pull request by xavfernandez**

### CODE REVIEW

**Comment by plq** [comment]
this is fine, but you lost the original patch?

https://github.com/xavfernandez/spyne/commit/7acb7dd7c40328548fa872a79220eea9ca25da1d

**Comment by xavfernandez** [comment]
Well the original patch is not needed since the case of a bare body_style with empty param is not allowed anymore.

**Comment by plq** [comment]
For correctness' sake, I'll still put it there. Thanks for your close interest!

**Comment by plq** [comment]
weeellll.... naah it's better like this :)

**Comment by xavfernandez** [comment]
:)

**Pull request merged**
