### PR TITLE
Fix _bytes_join behavior in Python3

### LINKED ISSUE #665: Python3 - TypeError: sequence item 0: expected a bytes-like object, int found
Spyne 2.13.16

## Description

Using `in_protocol=HttpRpc()` and `File`-type argument in service method I get error in Python 3.7:
```
TypeError: sequence item 0: expected a bytes-like object, int found
``` 

In Python 2.7 all worked as expected.
<details>
  <summary>Spoiler: Full traceback...</summary>

```
sequence item 0: expected a bytes-like object, int found
Traceback (most recent call last):
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/model/binary.py", line 136, in from_urlsafe_base64
    return (urlsafe_b64decode(_bytes_join(value)),)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/util/__init__.py", line 93, in _bytes_join
    return joiner.join(val)
TypeError: sequence item 0: expected a bytes-like object, int found
Traceback (most recent call last):
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/model/binary.py", line 136, in from_urlsafe_base64
    return (urlsafe_b64decode(_bytes_join(value)),)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/util/__init__.py", line 93, in _bytes_join
    return joiner.join(val)
TypeError: sequence item 0: expected a bytes-like object, int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/server/wsgi.py", line 305, in __call__
    return self.handle_rpc(req_env, start_response)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/server/wsgi.py", line 424, in handle_rpc
    self.get_in_object(p_ctx)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/server/_base.py", line 92, in get_in_object
    message=self.app.in_protocol.REQUEST)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/http.py", line 267, in deserialize
    ctx.descriptor.in_message, self.validator, req_enc=req_enc)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/dictdoc/simple.py", line 210, in simple_dict_to_object
    req_enc, validator)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/dictdoc/simple.py", line 126, in _to_native_values
    self.binary_encoding)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/_inbase.py", line 253, in from_unicode
    return handler(class_, string, *args, **kwargs)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/_inbase.py", line 566, in file_from_bytes
    return File.Value(data=binary_decoding_handlers[encoding](value))
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/model/binary.py", line 144, in from_urlsafe_base64
    raise ValidationError(value[:100] + "(...)")
TypeError: can't concat str to bytes
127.0.0.1 - - [07/Aug/2021 21:45:27] "POST /FileContentService/FileContent HTTP/1.1" 500 59
sequence item 0: expected a bytes-like object, int found
Traceback (most recent call last):
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/model/binary.py", line 136, in from_urlsafe_base64
    return (urlsafe_b64decode(_bytes_join(value)),)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/util/__init__.py", line 93, in _bytes_join
    return joiner.join(val)
TypeError: sequence item 0: expected a bytes-like object, int found
Traceback (most recent call last):
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/model/binary.py", line 136, in from_urlsafe_base64
    return (urlsafe_b64decode(_bytes_join(value)),)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/util/__init__.py", line 93, in _bytes_join
    return joiner.join(val)
TypeError: sequence item 0: expected a bytes-like object, int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/server/wsgi.py", line 305, in __call__
    return self.handle_rpc(req_env, start_response)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/server/wsgi.py", line 424, in handle_rpc
    self.get_in_object(p_ctx)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/server/_base.py", line 92, in get_in_object
    message=self.app.in_protocol.REQUEST)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/http.py", line 267, in deserialize
    ctx.descriptor.in_message, self.validator, req_enc=req_enc)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/dictdoc/simple.py", line 210, in simple_dict_to_object
    req_enc, validator)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/dictdoc/simple.py", line 126, in _to_native_values
    self.binary_encoding)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/_inbase.py", line 253, in from_unicode
    return handler(class_, string, *args, **kwargs)
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/protocol/_inbase.py", line 566, in file_from_bytes
    return File.Value(data=binary_decoding_handlers[encoding](value))
  File "/home/shtoltz/work/spyne_error/venv3/lib/python3.7/site-packages/spyne/model/binary.py", line 144, in from_urlsafe_base64
    raise ValidationError(value[:100] + "(...)")
TypeError: can't concat str to bytes
```

</details>

In Python 3 iterate over bytes return `int` value on each step. `joiner.join(val)` will not work if `val` is bytes type.
https://github.com/arskom/spyne/blob/354723434db322e87a37b98a8a62b731954651e7/spyne/util/__init__.py#L92-L93

So we need check `val` type and if it is`bytes` return `val` immediately:
```python
    def _bytes_join(val, joiner=b''):
        if isinstance(val, six.binary_type):
            return val
        return joiner.join(val)
```

Also, I assume that code
https://github.com/arskom/spyne/blob/354723434db322e87a37b98a8a62b731954651e7/spyne/model/binary.py#L141-L144
must look something like this (changed `>` to `<` and add `b"`):
```python
            if len(value) < 100:
                raise ValidationError(value)
            else:
                raise ValidationError(value[:100] + b"(...)")
```

## Example to reproduce
server.py
```python
# coding: utf-8
from spyne import ServiceBase, Unicode, rpc, Application, File
from spyne.protocol.http import HttpRpc
from spyne.protocol.json import JsonDocument
from spyne.server.wsgi import WsgiApplication


class FileContentService(ServiceBase):

    @rpc(File, _returns=Unicode)
    def FileContent(ctx, file_obj):
        return file_obj.data[0].decode('utf-8')


application = Application(
    [FileContentService],
    tns='spyne.examples.hello',
    in_protocol=HttpRpc(),
    out_protocol=JsonDocument(),
)

if __name__ == '__main__':
    from wsgiref.simple_server import make_server

    wsgi_app = WsgiApplication(application)
    server = make_server('127.0.0.1', 9000, wsgi_app)
    server.serve_forever()

```

client.py
```python
# coding: utf-8
from base64 import urlsafe_b64encode

import requests

file_data = b'Text file content'

res = requests.post(
    'http://127.0.0.1:9000/FileContentService/FileContent',
    data={
        'file_obj': urlsafe_b64encode(file_data),
    },
)
print(res.status_code)
print(res.content)

```

### PR DESCRIPTION
**Pull request by shtoltz**
Fix #665

### CODE REVIEW

**Comment by plq** [comment]
Hey, thanks for the pull request.

First things first:

> [Number of the Beast !!!](https://www.youtube.com/watch?v=7-iRf9AWoyE)

**Comment by plq** [comment]
Jenkins, run tests

**Review by plq — APPROVED** [review]
these look fine to me

**Comment by plq** [comment]
Jenkins, run tests please.

**Comment by plq** [comment]
Jenkins, run tests

**Comment by shtoltz** [comment]
@plq Thanks!

**Comment by plq** [comment]
np, sorry about the CI/review noise. it's fixed now.

**Pull request merged**
