### PR TITLE
Allow defaults to be applied in a JSON document

### PR DESCRIPTION
**Pull request by knoxsp**
When using default values on complexmodels in soap, the defaults are applied correctly and hence validation is passed, but when using json documents with a 'soft' validation, they are not applied, causing the validation to fail.

This change checks if a default is available, and if the attribute is not set. If so, the default is applied.

### CODE REVIEW

**Comment by plq** [comment]
Can you please add a test case that fails? Modifying `_from_dict_value` won't be enough if the issue is where I think it is.

**Comment by knoxsp** [comment]
Hi, I have added a unit tests that demonstrates the change I made.
I wasn't entirely sure what you were asking for, but hopefully this will be useful at least.
If I have added this test to the incorrect place, or i need to add another test, let me know and I will add the appropriate tests / fixes.

**Comment by plq** [comment]
Ok, so the `{"b":null}` fragment there is valid and it's expected behaviour from Spyne's part to not replace it with its default value. if you want null values to fail, you must set `nullable=False`

**Comment by plq** [comment]
default values are only used when the value is missing, not when it's null.

**Comment by knoxsp** [comment]
Understood, thank you.
The second assertion in the unit test should not fail then? Because I've 
said that 'b' has a default
but that default has not been assigned?

**Comment by plq** [comment]
Yes, as there's no error `ctx.in_error` should evaluate to `None`

**Comment by knoxsp** [comment]
OK. Thanks. Where is the most appropriate place to sort this issue out?
It'll save me having to step through the soap implementation :)

Thanks for your help.

**Comment by plq** [comment]
Ah, so soap implementation DOES replace null values with defaults? That's a bug in soap protocol!

**Comment by knoxsp** [comment]
No, I was just wondering where the 'adding a default value' code is in 
the soap protocol so I can put the code into the
equivalent place in the JSON protocol. (I'll double check the soap 
protocol now, just in case!)

**Comment by plq** [comment]
http://www.w3.org/TR/xmlschema-1/#Element_Declaration_details does not use a precise enough language, imho.

Let

```
{value constraint}
    Optional. A pair consisting of a value and one of default, fixed.
```

Where

> {value constraint} establishes a default or fixed value for an element. If default is specified, and if the element being ·validated· is empty, then the canonical form of the supplied constraint value becomes the [schema normalized value] of the ·validated· element in the ·post-schema-validation infoset·. If fixed is specified, then the element's content must either be empty, in which case fixed behaves as default, or its value must match the supplied constraint value.


>> Note: The provision of defaults for elements goes beyond what is possible in XML 1.0 DTDs, and does not exactly correspond to defaults for attributes. In particular, an element with a non-empty {value constraint} whose simple type definition includes the empty string in its lexical space will nonetheless never receive that value, because the {value constraint} will override it.

**Comment by plq** [comment]
Ok, I just looked at this properly. Here's more info from schema primer[1]:

> The schema processor treats defaulted elements slightly differently. When an element is declared with a default value, the value of the element is whatever value appears as the element's content in the instance document; if the element appears without any content, the schema processor provides the element with a value equal to that of the default attribute. However, if the element does not appear in the instance document, the schema processor does not provide the element at all. In summary, the differences between element and attribute defaults can be stated as: *Default attribute values apply when attributes are missing, and default element values apply when elements are empty*. 

(emphasis mine)

So, empty means the value is 1) provided 2) is marked null. If those two conditions hold true at the same time, the default is passed over to the user code.

This means missing values have to remain uninitialized (in Python world, that means None) even when you've specified a default value. You need the client to provide you an explicit null for the default values to work. So defaults would only work when `minOccurs=1` and `nullable=True`

For XmlDocument, Spyne currently replaces both missing and null values with default values. I intend to keep it that way because I find it unintuitive to require `minOccurs=1` to have default values work.

For other protocols, Spyne currently replaces only missing values with default values and leaves the explicit nulls untouched.

I'd prefer Spyne behaviour to be standard on all protocols to keep things simple. However, as we can't force that for XML (it's against the standard), I've added a flag to XmlDocument -- `replace_null_with_default` which lets the user tweak this behaviour. It's `True` by default for backwards-compatibility concerns.

Now as for your question, 

[1]: http://www.w3.org/TR/xmlschema-0/

**Comment by plq** [comment]
I hope this solves the issue.

**Pull request closed without merging**
