### PR TITLE
Error condition has been deleted

### PR DESCRIPTION
**Pull request by Faoxis**
The library doesn't work correctly with it.

### CODE REVIEW

**Comment by plq** [comment]
Hey, this is there so you don't pass something that spyne doesn't use by mistake. (e.g. you type _return instead of _returns, or miss the underscore or whatever) 

i can't see how is could this be an issue for you to be honest.

**Comment by Faoxis** [comment]
But I have an error with `_port_type` parameter. Early It works perfectly, what's happened with this parameter in new version ?

**Comment by Faoxis** [comment]
This is `traceback`:
```
Traceback (most recent call last):
  File "/home/samojlov/myprojects/temp/iotchottest/run.py", line 12, in <module>
    from app.views.api.autorization import AutorizationService
  File "/home/samojlov/myprojects/temp/iotchottest/app/views/api/autorization.py", line 41, in <module>
    class AutorizationService(spyne.Service):
  File "/home/samojlov/myprojects/temp/iotchottest/venv/src/flask-spyne/flask_spyne/flask_spyne.py", line 111, in __init__
    ServiceBaseMeta.__init__(cls, name, bases, dict)
  File "/home/samojlov/myprojects/temp/iotchottest/venv/local/lib/python2.7/site-packages/spyne/service.py", line 49, in __init__
    descriptor = v(_default_function_name=k)
  File "/home/samojlov/myprojects/temp/iotchottest/venv/local/lib/python2.7/site-packages/spyne/decorator.py", line 382, in explain_method
    raise Exception("Unknown kwarg(s) %r passed.", kparams)
Exception: ('Unknown kwarg(s) %r passed.', {'_port_type': 'GetPassword'})

```

**Comment by plq** [comment]
it was renamed to `_soap_port_type`

**Comment by plq** [comment]
reopen if not happy

**Pull request closed without merging**
