### PR TITLE
fixes so now multiple calls of same rpc method instance work and adds missing PositiveInteger model

### PR DESCRIPTION
**Pull request by JacekPliszka**
Same as:

https://github.com/arskom/spyne/pull/500

But travis build fails at 2_12 - maybe it works at amster

### CODE REVIEW

**Comment by plq** [comment]
can you please elaborate on b32920c a little bit?

**Comment by JacekPliszka** [comment]
This is a very small change:

1. PositivieInteger was missing in model/primitive/__init__.py so I added it

2. pop was called on kwargs what caused that given function could be called just once - fine for separate process for each call situation but not acceptable when we want to make several calls to given instance (unit tests or some optimized environments)

I sent the same patch to 2.12 as it is the current stable branch.

**Comment by plq** [comment]
1. OK
2. I still can't understand how this works. Can you write a test case for this? The `@rpc` decorator is only used *once* to put type markers in MethodDescriptor. I can see the change you do is totally harmless but I'd like to fully understand what you are doing to maybe help you better.

Thanks!

**Comment by JacekPliszka** [comment]
Ad 2. OK, I can see that our implementation might be the problem. You can add the code below to spyne/spyne/test/test_null_server.py and run nosetests -s  test_null_server.py
```
class Service1(object):
    @spyne.rpc(String, _returns=String, _soap_body_style='wrapped')
    def getInfo(ctx, request):
        return 'Correct result'


class Service2(object):
    @spyne.rpc(String, _returns=String, _soap_body_style='wrapped')
    def getInfo2(ctx, request):
        return 'Correct result'


class MySpyneApp(object):
    def __new__(cls, *args, **kwargs):
        methods = []
        import inspect
        for service in [Service1, Service2]:
            service_methods = inspect.getmembers(
                service, predicate=inspect.ismethod
            )

            methods.extend(
                (k, object.__getattribute__(service, k))
                for k, v in service_methods if getattr(v, '_is_rpc', False)
            )

        methods = dict(methods)

        MyService = type('MyService', (spyne.ServiceBase,), methods)

        app = spyne.Application(
            [MyService],
            'TEST',
            in_protocol=Soap11(validator='schema'),
            out_protocol=Soap11(validator='schema')
        )
        return app


class TestNullServer2(unittest.TestCase):
    request_name = '{http://www.w3.org/2001/XMLSchema}string'
    request_payload_class = None

    def setUp(self):
        super(TestNullServer2, self).setUp()
        self._server = NullServer(MySpyneApp(), ostr=False)

    def test_first(self):
        result = self._server.service.getInfo(spyne.Unicode)
        print "In one test: ", result
        self.assertIsNotNone(result)

    def test_second(self):
        result = self._server.service.getInfo(spyne.Unicode)
        print "In another test:", result
        self.assertIsNotNone(result)
```

**Pull request closed without merging**
