### PR TITLE
customizable exception string

### PR DESCRIPTION
**Pull request by DmitriyMoseev**
Hello.
Spyne returns "Internal Error" on any unhandled exception now.
I propose to make it customizable. It will be useful when all clients are yours and you do not need to worry about security.

### CODE REVIEW

**Comment by plq** [comment]
So sorry, I meant `call_wrapper`\.

https://github.com/arskom/spyne/blob/79f8120668ec471097f410e63fa48cdf797fae7a/spyne/service.py#L201

**Comment by plq** [comment]
ping

**Comment by DmitriyMoseev** [comment]
You are absolutely right. I have got the behavior I wanted just overriding call_wrapper. So I do not need this pullrequest now. Thank you!

**Comment by plq** [comment]
sure :)

**Comment by DXist** [comment]
There are issues with catching original exception in `call_wrapper` and logging setup:

You may
1. do custom logging inside `call_wrapper` and have to deal with duplicate logging in [Application.process_request](https://github.com/arskom/spyne/blob/master/spyne/application.py#L163)
2. omit logging inside `call_wrapper` and lose original exception info.

There is an option to mute loggers of `spyne.application` and do all exception handling inside `call_wrapper`. In this case an error occurred after calling of `call_wrapper` will be silent. This can be fixed by introducing separate logger for [exception catching block](https://github.com/arskom/spyne/blob/79f8120668ec471097f410e63fa48cdf797fae7a/spyne/application.py#L173).

**Comment by plq** [comment]
let's get rid of exception logging in application?

**Comment by DXist** [comment]
There should be good defaults. One way to customize them is to introduce `BaseApplication` class without logging implementation. And `Application` could work with default implementation.

**Comment by plq** [comment]
There are already too many function calls there, I would not be happy to add another to the hot path there.

**Comment by plq** [comment]
adding a logger_server to the broad exception catching block is fine by me though

**Comment by DXist** [comment]
This is fine by me too.

**Pull request closed without merging**
