### PR TITLE
Update test matrix to supported Python/Django combinations

### PR DESCRIPTION
**Pull request by antonagestam**
- Minor formatting changes
- Remove unused import

### CODE REVIEW

**Comment by plq** [comment]
This looks good. My only objection is the suppression of Python 2.7 targets. I'm planning to support 2.7 for as long as I can. Could you please add back the pair of 2.7 along with the with the latest Django release that supports it? I'm OK even if this version is unsupported by the Django community.

**Comment by antonagestam** [comment]
Sure, Django 1.11 is the last Django version to support Python 2.7, I'll add that combination. For reference I've used these pages to determine which version combinations to keep:

- https://docs.djangoproject.com/en/3.0/releases/1.11/
- https://docs.djangoproject.com/en/3.0/releases/2.2/
- https://docs.djangoproject.com/en/3.0/releases/3.0/
- https://www.djangoproject.com/download/

A simplification of the matrix changes after I add back 2.7 are:

- Drop support for Django 1.8
- Drop support for Django 2.0
- Drop support for Django 2.1
- Add support for Django 2.2
- Add support for Django 3.0
- Drop support for Python 3.4
- Add support for Python 3.8

**Comment by antonagestam** [comment]
Sorry, I might have misread your comment, did you want to keep `py27-dj18` as well?

**Comment by plq** [comment]
Just the latest version that supports 2.7 would be enough.

**Comment by plq** [comment]
Jenkins, run stable tests.

**Comment by plq** [comment]
Jenkins, run tests

**Comment by plq** [comment]
Brilliant. Thanks a lot for your help.

**Comment by antonagestam** [comment]
@plq Thanks for reviewing and merging so quickly! 🙏

**Pull request merged**
